development: 
  cloud_name: "devsinc-shahrukh-fazal213213231"
  api_key: "235691447557591"
  api_secret: "D_jVa9dBAjf3FOTm4lW3ip-wM94"
  secure: true

production:
  cloud_name: "devsinc-shahrukh-fazal213213231"
  api_key: "235691447557591"
  api_secret: "D_jVa9dBAjf3FOTm4lW3ip-wM94"
  secure: true